# Generated by Django 5.2.8 on 2025-11-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productivity_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETED'), ('I', 'INPROGRESS'), ('N', 'NOTSTARTED')], default='N', max_length=1),
        ),
    ]
